### ISSUE TITLE
error using this plugin

### ISSUE THREAD

**Issue by rbenzazon** [cyco130/svelte-kit-node-loader#2]
Hello,
Thanks for helping with this debug issue ! I'm trying to use the plugin in my existing project.
I installed it
```bash
pnpm install -D @vavite/node-loader 
```
then modified vite.config.js : 
```javascript
...
import { nodeLoaderPlugin } from "@vavite/node-loader/plugin";
...

...
plugins: [nodeLoaderPlugin(),sveltekit()],
...
```
then added the command in the dev script (package.json) : 
```json
{
/*...*/
"scripts": {
		"dev": "vavite-loader vite dev",
/*...*/
}
```
now regardless if I use the javascript debug terminal or not I get a terminal error (same twice in a row) whenever I try to visit a page in dev mode : 
```bash
Error: Could not find node for /@fs/Users/rmp/Documents/templates_npm/personal-media-lib-svelte/node_modules/.pnpm/@sveltejs+kit@1.3.10_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/components/error.svelte
    at resolve (file:///C:/Users/rmp/Documents/templates_npm/personal-media-lib-svelte/node_modules/.pnpm/@sveltejs+kit@1.3.10_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:74:27)
    at async result.component (file:///C:/Users/rmp/Documents/templates_npm/personal-media-lib-svelte/node_modules/.pnpm/@sveltejs+kit@1.3.10_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:131:46)
    at async Promise.all (index 1)
    at async render_response (vite:/@fs/C:/Users/rmp/Documents/templates_npm/personal-media-lib-svelte/node_modules/.pnpm/@sveltejs+kit@1.3.10_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:92:16)
    at async respond_with_error (vite:/@fs/C:/Users/rmp/Documents/templates_npm/personal-media-lib-svelte/node_modules/.pnpm/@sveltejs+kit@1.3.10_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:82:10)
    at async render_page (vite:/@fs/C:/Users/rmp/Documents/templates_npm/personal-media-lib-svelte/node_modules/.pnpm/@sveltejs+kit@1.3.10_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:322:10)
    at async resolve (vite:/@fs/C:/Users/rmp/Documents/templates_npm/personal-media-lib-svelte/node_modules/.pnpm/@sveltejs+kit@1.3.10_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:362:17)
    at async Object.handle (file:///C:/Users/rmp/Documents/templates_npm/personal-media-lib-svelte/packages/front/src/hooks.server.ts?t=1678621963842:23:20)
    at async respond (vite:/@fs/C:/Users/rmp/Documents/templates_npm/personal-media-lib-svelte/node_modules/.pnpm/@sveltejs+kit@1.3.10_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:233:20)
    at async file:///C:/Users/rmp/Documents/templates_npm/personal-media-lib-svelte/node_modules/.pnpm/@sveltejs+kit@1.3.10_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:498:22
```
I did get a breakpoint to work from source code yeah! and the debugger goes to the source code too but the page render doesn't work.
Did I miss something in the setup maybe ? I just updated vite to the latest version. The rest of the project was fully updated a couple of weeks ago.
Regards

**Comment by cyco130** [comment]
Can you provide a minimal reproduction?

It fails to resolve a module but I'll need a reproduction to track down the exact problem.

**Comment by rbenzazon** [comment]
I'll have to create a new project for that. Can you confirm that the steps I took to setup are complete? I haven't found any documentation.

**Comment by cyco130** [comment]
Hi,

I just caught something that may or may not be causing this error. Can you try with the canary version (`npm install @vavite/node-loader@canary`).

If still no good, I'm gonna need a minimal reproduction. Your setup seems correct to me.
